name: smartdinner
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
    
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.6
  firebase_app_check: ^0.3.2+5
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/dark.png
    - assets/images/white.png
    - .env
